### ISSUE TITLE
Caching Bug

### ISSUE THREAD

**Issue by davidrans** [jfcherng/php-sequence-matcher#2]
I ran into a runtime bug using the https://github.com/jfcherng/php-diff library.

I dug into the source and narrowed it down to a caching issue. When the `SequenceMatcher` is re-used, the cache isn't getting properly cleared in some cases.

I managed to reproduce it by changing the "old" value, but not the "new" value. Here's a failing test I wrote:
```
public function testCachingBug(): void         
{                                           
    $old = ['a'];                           
    $new = ['a', 'b', 'c'];                 
                                            
    $this->sm->setSeq1($old)->setSeq2($new);
                                            
    $old = ['a', 'b'];                      
    $new = ['a', 'b', 'c'];                 
                                            
    $this->sm->setSeq1($old)->setSeq2($new);

    // Throws ErrorException: "Undefined array key 1" 
    $this->sm->getOpcodes();                
}                                           
```

**Comment by jfcherng** [comment]
Thanks. This should've been fixed in https://github.com/jfcherng/php-sequence-matcher/commit/b4b20fb03ea0b1a01bcd77e66811ea3ec046a8d2 and release `3.2.8`.

**Comment by davidrans** [comment]
Thank you!
